### ISSUE TITLE
 TypeError: Cannot set property 'port' of undefined

### ISSUE THREAD

**Issue by gigamedard** [AlgoTrader/betfair-sports-api#12]
Hi I was so thank full  and exited when found this api and the turtotial .So i started to dot everything that a step ask . when I try to run the code of login I get this error:

`
C:\betfair\node_modules\betfair-sports-api>node login.js
C:\betfair\node_modules\betfair-sports-api\util\forever.js:113
  options.port = port
               ^

TypeError: Cannot set property 'port' of undefined
    at ForeverAgentSSL.createConnectionSSL [as createConnection] (C:\betfair\nod
e_modules\betfair-sports-api\util\forever.js:113:16)
    at ForeverAgentSSL.Agent.createSocket (_http_agent.js:175:16)
    at ForeverAgentSSL.Agent.addRequest (_http_agent.js:144:23)
    at ForeverAgentSSL.ForeverAgent.addRequest (C:\betfair\node_modules\betfair-
sports-api\util\forever.js:66:10)
    at new ClientRequest (_http_client.js:131:16)
    at Object.exports.request (http.js:31:10)
    at Object.socket.once.exports.request (https.js:182:15)
    at BetfairInvocation.execute (C:\betfair\node_modules\betfair-sports-api\lib
\betfair_invocation.js:157:25)
    at BetfairSession.open (C:\betfair\node_modules\betfair-sports-api\lib\betfa
ir_session.js:41:11)
    at Object.<anonymous> (C:\betfair\node_modules\betfair-sports-api\login.js:9
:9)`

do someone can help me please!

**Comment by AlgoTrader** [comment]
Please stop to use obsolete API. This is legacy repo
